---
- name: prepares MQ server
  hosts: mqservers
  become: true
  environment:
    PATH: /opt/mqm/bin:{{ ansible_env.PATH }}
  collections:
    - ibm.ibmmq

  tasks:
    - name: Import downloadmq role
      ansible.builtin.import_role:
        name: ibm_messaging.ibmmq.downloadmq

    - name: Import setupusers role
      ansible.builtin.import_role:
        name: ibm_messaging.ibmmq.setupusers

    - name: Import installmq role
      ansible.builtin.import_role:
        name: ibm_messaging.ibmmq.installmq

    - name: Import setupenvironment role
      ansible.builtin.import_role:
        name: ibm_messaging.ibmmq.setupenvironment

    - name: Create a queue manager
      become_user: mqm
      tags: ["queue"]
      ibm_messaging.ibmmq.queue_manager:
        qmname: queue_manager_12
        state: present

    # Make sure to have a MQSC file in the same directory you will run this playbook from
    - name: Use MQSC File
      become_user: mqm
      ibm_messaging.ibmmq.queue_manager:
        qmname: queue_manager_12
        state: running
        mqsc_file: files/dev-config.mqsc